name: CI Pipeline with Integrated Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SonarScanner CLI
        uses: actions/cache@v2
        with:
          path: sonar-scanner-cli
          key: sonar-scanner-cli-${{ runner.os }}-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: sonar-scanner-cli

      - name: Run SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=jiangbw_vlv-eMSP \
            -Dsonar.organization=jiangbw \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}